name: golangci-lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - 'releases/**'
    paths:
      - '**.go'
      - '**go.mod'
      - '**go.sum'
      - '!tilt_modules/**'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2  # https://github.com/golangci/golangci-lint/releases
          working-directory: ${{matrix.working-directory}}