name: verify
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - 'releases/**'
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Verify Boilerplate
        run: make verify-boilerplate
      - name: Verify Modules
        run: make verify-modules
      - name: Verify gen
        run: make verify-gen